export const lang = {
  eng: {
    bookAppointment: 'Book Appointment',
    back: 'Back',
    nextStep: 'Next Step',
    addToCalendar: 'Add to Calendar',
    print: 'Print',
    summary: 'Summary',
    appointmentInfo: 'Appointment Info',
    date: 'Date',
    time: 'Time',
    agent: 'Agent',
    service: 'Service',
    extras: 'Extras',
    totalPrice: 'Total Price',
    customerInfo: 'Customer Info',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    questions: 'Questions?',
    callForHelp: 'Call (858) 939-3746 for help',
    selectService: 'Select Service',
    selectServiceDesc: 'Please select a service you want to schedule appointment for.',
    selectServiceExtras: 'Select Service Extras',
    selectServiceExtrasDesc: 'Select service extras you want to add to your booking.',
    selectAgent: 'Select Agent',
    selectAgentDesc: 'You can pick a specific agent to perform your service or select any to automatically assign you one.',
    selectDateTime: 'Select Date & Time',
    selectDateTimeDesc: 'Click on a date to see a timeline of available slots, click on a green time slot to reserve it.',
    enterInformation: 'Enter Information',
    enterInformationDesc: 'Please provide your contact details so we can send you a confirmation and other contact info',
    confirmation: 'Confirmation',
    confirmationDesc: 'Handles different career a accordingly, after a of the for found customary feedback by happiness',
  },
};
